export const eventDeck = [
  {
    id: "coolant-valve-chatter",
    title: "Coolant Valve Chatter",
    severity: "mild",
    description: "A coolant bypass valve chatters against its stop and sheds heat unevenly.",
    effects: { heat: 2 },
  },
  {
    id: "archive-noise",
    title: "Archive Bus Noise",
    severity: "mild",
    description: "The archive spine emits recovery chatter on a maintenance bus.",
    effects: { signal: 4 },
  },
  {
    id: "quiet-cycle",
    title: "Quiet Cycle",
    severity: "mild",
    description: "No immediate fault escalations. Background repair drones continue their patrol.",
    effects: { hull: 1, heat: -2 },
  },
  {
    id: "ghost-carrier",
    title: "Unknown Carrier",
    severity: "mild",
    description: "Sensors detect a repeating transmission on a decommissioned crew channel.",
    effects: { signal: 8 },
  },
  {
    id: "radiator-frost",
    title: "Radiator Frost Shedding",
    severity: "mild",
    description: "A radiator panel sheds frozen volatiles and briefly improves heat rejection.",
    effects: { heat: -4 },
  },
  {
    id: "battery-rebalance",
    title: "Reserve Cell Rebalance",
    severity: "mild",
    description: "A reserve cell stack accepts charge after a delayed balancing cycle.",
    effects: { power: 5 },
  },
  {
    id: "sealed-cabin-vent",
    title: "Sealed Cabin Vent",
    severity: "mild",
    description: "A sealed crew cabin equalizes into the active atmosphere loop.",
    effects: { oxygen: 3 },
  },
  {
    id: "probe-echo",
    title: "Probe Echo",
    severity: "mild",
    description: "An old survey probe returns a partial navigation echo.",
    effects: { signal: 6 },
  },
  {
    id: "micro-leak",
    title: "Micro Leak",
    severity: "mild",
    description: "A hairline seal leak lowers the active loop pressure before isolation.",
    effects: { oxygen: -3 },
  },
  {
    id: "dust-static",
    title: "Dust Static",
    severity: "mild",
    description: "Electrostatic dust collects along the sensor mast grounding path.",
    effects: { signal: -3 },
  },
  {
    id: "micro-impact",
    title: "Micrometeor Shear",
    severity: "moderate",
    description: "A brief impact storm crosses the forward hull plating.",
    effects: { hull: -7, heat: 3 },
  },
  {
    id: "oxygen-variance",
    title: "Pressure Variance",
    severity: "moderate",
    description: "Life support loop B reports oxygen loss through an unlisted valve path.",
    effects: { oxygen: -8 },
  },
  {
    id: "reactor-overcorrection",
    title: "Reactor Overcorrection",
    severity: "moderate",
    description: "The reactor overcorrects after a delayed coolant response.",
    effects: { power: -6, heat: 8 },
  },
  {
    id: "relay-bus-drop",
    title: "Relay Bus Drop",
    severity: "moderate",
    description: "A grid relay falls back to standby routing and wastes stored reserve.",
    effects: { power: -9 },
  },
  {
    id: "scrubber-saturation",
    title: "Scrubber Saturation",
    severity: "moderate",
    description: "CO2 scrubber media saturates faster than the loop controller predicted.",
    effects: { oxygen: -6, heat: 2 },
  },
  {
    id: "thermal-soak",
    title: "Thermal Soak",
    severity: "moderate",
    description: "Heat bleeds from an insulated conduit into adjacent habitable sections.",
    effects: { heat: 9 },
  },
  {
    id: "fuel-line-purge",
    title: "Fuel Line Purge",
    severity: "moderate",
    description: "Propulsion purges contaminated maneuvering reserve from a cold feed line.",
    effects: { fuel: -7 },
  },
  {
    id: "sensor-desync",
    title: "Sensor Timebase Desync",
    severity: "moderate",
    description: "Sensor clocks drift out of agreement and discard several weak returns.",
    effects: { signal: -7 },
  },
  {
    id: "archive-recovery-window",
    title: "Archive Recovery Window",
    severity: "moderate",
    description: "A cold archive bank wakes long enough to correlate missing signal fragments.",
    effects: { signal: 10, power: -3 },
  },
  {
    id: "hull-flex",
    title: "Hull Flexure",
    severity: "moderate",
    description: "The long spine flexes under thermal stress and opens old repair seams.",
    effects: { hull: -5, heat: 5 },
  },
  {
    id: "coolant-contamination",
    title: "Coolant Contamination",
    severity: "moderate",
    description: "Conductive particulate enters a secondary coolant branch.",
    effects: { heat: 7, power: -4 },
  },
  {
    id: "emergency-drone-assist",
    title: "Emergency Drone Assist",
    severity: "moderate",
    description: "A maintenance drone completes an undocumented hull patch before losing telemetry.",
    effects: { hull: 6, power: -4 },
  },
  {
    id: "hard-radiation-front",
    title: "Hard Radiation Front",
    severity: "severe",
    description: "A hard radiation front disrupts exposed buses and blinds part of the sensor mast.",
    effects: { hull: -8, power: -8, signal: -10 },
  },
  {
    id: "reactor-surge",
    title: "Reactor Surge",
    severity: "severe",
    description: "The reactor climbs past the requested output band before control rods answer.",
    effects: { power: -10, heat: 14 },
  },
  {
    id: "major-pressure-loss",
    title: "Major Pressure Loss",
    severity: "severe",
    description: "A pressure bulkhead fails to seal and vents atmosphere into a dormant section.",
    effects: { oxygen: -14, hull: -4 },
  },
  {
    id: "meteorite-puncture",
    title: "Meteorite Puncture",
    severity: "severe",
    description: "A high-velocity fragment punches through external plating near a service crawl.",
    effects: { hull: -14, oxygen: -5 },
  },
  {
    id: "thermal-runaway",
    title: "Thermal Runaway",
    severity: "severe",
    description: "A heat exchanger loop saturates and dumps stored heat into the core bay.",
    effects: { heat: 18 },
  },
  {
    id: "propellant-flash-boil",
    title: "Propellant Flash Boil",
    severity: "severe",
    description: "A reserve tank flash-boils through a relief path after insulation failure.",
    effects: { fuel: -15, heat: 5 },
  },
  {
    id: "grid-collapse",
    title: "Grid Collapse",
    severity: "severe",
    description: "The main grid browns out and emergency buses shed nonessential loads.",
    effects: { power: -16, signal: -5 },
  },
  {
    id: "archive-index-cascade",
    title: "Archive Index Cascade",
    severity: "severe",
    description: "The archive indexer repeats a failed reconstruction across live memory banks.",
    effects: { signal: -12, power: -6 },
  },
];
